language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - qpm check
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.8.0
    - source qt-5.8.0.env
    - mkdir build
    - cd build
    - run-unittests ../tests/snapshottestingunittests/snapshottestingunittests.pro
    - cd..
    - qpm 
    - cd examples/example1
    - qmake
    - make

